### ISSUE TITLE
DAS problem

### ISSUE THREAD

**Issue by mjeitler** [dmwm/das2go#23]

**Comment by mjeitler** [comment]
I am looking for CMS data using this query 
dataset=/*RelValTTbar_13*/*/GEN-SIM*  site=T1_CH_CERN
and I am told there are no data available, which I cannot believe. 
When I just query for dataset=/*RelValTTbar_13*/*/GEN-SIM*   I get lots of records but all the files I have tried to find using 
eos ls -alF /eos/cms/store/.....
do not exist.
How can I find data with really existing files? Even adding 
status=VALID*
does not help.

Thanks for your help!
Manfred Jeitler

**Comment by vkuznet** [comment]
Manfred,
it is nothing wrong with DAS per-se, it is issue with your dataset/file discovery. Why are you assuming that your data resides on T1_CH_CERN? The discovery process should be the following:
- find datasets you are interested in, e.g.
```
dataset=/*RelValTTbar_13*/*/GEN-SIM*
```
- out of provided list find sites where it is reside, e.g.
```
site dataset=/RelValTTbar_13_UP18/CMSSW_11_0_0_pre6-110X_upgrade2018_realistic_v3_FastSim-v1/GEN-SIM-DIGI-RECO
```
- if you know the site now you can look at pattern datasets at that site, e.g.
```
dataset dataset=/*RelValTTbar_13*/*/GEN-SIM*  site=T2_CH_CERN
```
- if you need files from this dataset you can look them up too, e.g.
```
file dataset=/RelValTTbar_13_UP18/CMSSW_11_0_0_pre6-110X_upgrade2018_realistic_v3_FastSim-v1/GEN-SIM-DIGI-RECO site=T2_CH_CERN
```
etc.

I don't know what you're doing and can't guide you more, but this is pretty simple and logical recipe. And for files download I doubt that you can locate them at EOS, instead you should request to transfer those to your site via phedex or use xrdcp command.

Closing the ticket since it is not issue with DAS.

**Comment by mjeitler** [comment]
Dear Valentin,

Thank you for the reply! I am not assuming anything, I just need some RAW data to produce test vectors for the Global Trigger of CMS.

I would like to access them from CMSSW (preferably without copying if possible - but if it’s easier to copy them I can do that, too) like this:

====
process.source = cms.Source("PoolSource",
    secondaryFileNames = cms.untracked.vstring(),
    fileNames = cms.untracked.vstring(
       '/store/relval/CMSSW_10_1_0/RelValTTbar_13/GEN-SIM-DIGI-RAW/101X_upgrade2018_design_v7_resub-v1/10000/5C7E71FC-E037-E811-B0B4-0CC47A78A468.root',
====


I have tried to proceed as you suggest:
Typing

site dataset=/*RelValTTbar_13*/*/*RAW*

yields, among others,

________________________________
Site name: T2_CH_CERN<https://cmsweb.cern.ch/das/request?input=site%3DT2_CH_CERN&instance=prod/global>
StorageElement: srm-eoscms.cern.ch<http://srm-eoscms.cern.ch>
Datasets<https://cmsweb.cern.ch/das/request?instance=prod/global&input=dataset+site%3DT2_CH_CERN%2A> Sources: phedex hide


but when I then try

dataset=/*RelValTTbar_13*/*/*RAW*  site=T2_CH_CERN

I get

No results found
DAS unable to find any results for your query. Please revisit your query by reviewing DAS query guide<https://cmsweb.cern.ch/das/faq> or submit a DAS github   issue<https://github.com/dmwm/das2go/issues/new> to resolve your query request.


So I am a bit stuck. Sorry but I am new to DAS and would just like to find ANY files satisfying my requirements
( dataset=/*RelValTTbar_13*/*/*RAW* ), preferably sitting at CERN. If there are really none at CERN, can I access them by CMSSW as shown above or do I have to copy them?


Thanks a lot for your help!

Manfred





  ____  ____  ____  ____
 /\   \/\   \/\   \/\   \
/  \___\ \___\ \___\ \___\   Manfred Jeitler
\  /___/ /   / /   / /   /
 \//\   \___/\/___/\/___/   CERN EP, mailbox E02400,
  /  \___\    /  \___\       CH-1211 Geneva 23, Switzerland
  \  / __/_  _\  /   /   office +41 22 767 6307
   \/_/\   \/\ \/___/   office location: building 21, R-029
     /  \__/  \___\    mobile +41 75 411 0862
     \  / _\  /   /      (16-0862 from inside CERN)
      \/_/\ \/___/   home   +33 4 50 40 66 56
        /  \___\    fax    +41 22 766 7967
        \  /   /
         \/___/

On 4 Sep 2019, at 14:14, Valentin Kuznetsov <notifications@github.com<mailto:notifications@github.com>> wrote:


Manfred,
it is nothing wrong with DAS per-se, it is issue with your dataset/file discovery. Why are you assuming that your data resides on T1_CH_CERN? The discovery process should be the following:

  *   find datasets you are interested in, e.g.

dataset=/*RelValTTbar_13*/*/GEN-SIM*


  *   out of provided list find sites where it is reside, e.g.

site dataset=/RelValTTbar_13_UP18/CMSSW_11_0_0_pre6-110X_upgrade2018_realistic_v3_FastSim-v1/GEN-SIM-DIGI-RECO


  *   if you know the site now you can look at pattern datasets at that site, e.g.

dataset dataset=/*RelValTTbar_13*/*/GEN-SIM*  site=T2_CH_CERN


  *   if you need files from this dataset you can look them up too, e.g.

file dataset=/RelValTTbar_13_UP18/CMSSW_11_0_0_pre6-110X_upgrade2018_realistic_v3_FastSim-v1/GEN-SIM-DIGI-RECO site=T2_CH_CERN


etc.

I don't know what you're doing and can't guide you more, but this is pretty simple and logical recipe. And for files download I doubt that you can locate them at EOS, instead you should request to transfer those to your site via phedex or use xrdcp command.

Closing the ticket since it is not issue with DAS.

**Comment by vkuznet** [comment]
Manfred,
DAS has nothing to do how you'll use your data. DAS is a tool to discovery data but nothing else. With that in mind what you need to know is a little of DAS query language. The site query you place for dataset pattern is not supported since pattern can spawn many-many datasets and query will become slow. I provided a recipe for you and you should follow it. Look-up your datasets from dataset pattern, then for each dataset you are interested you can find a site (the site query requires full dataset path), and then you can find files you need.
