### ISSUE TITLE
Instabilities of DAS site dataset=/a/b/c queries

### ISSUE THREAD

**Issue by vkuznet** [dmwm/das2go#32]
I got report from Felipe Gómez-Cortés who claimed that DAS web UI provides different results for the following query:
```
site dataset=/ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM
```
After series of iterations I confirmed that this is the case using my dev environment. I identified that the problem is related to unability of DAS to contact with cms-rucio service yield the following errors:
```
2021/06/05 11:17:28 fetch.go:486: ERROR: fail to fetch http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#3ce2d95e-7168-11e6-9fb1-002590494fb0/datasets, retries 3, error Get "http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#3ce2d95e-7168-11e6-9fb1-002590494fb0/datasets": dial tcp: lookup cms-rucio.cern.ch: no such host
2021/06/05 11:17:28 fetch.go:486: ERROR: fail to fetch http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#c541fd04-7198-11e6-9fb1-002590494fb0/datasets, retries 3, error Get "http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#c541fd04-7198-11e6-9fb1-002590494fb0/datasets": dial tcp: lookup cms-rucio.cern.ch: no such host
```

We need to identify the source of this issue. @ericvaandering any ideas?

**Comment by ericvaandering** [comment]
I assume this is intermittent? The first thing I’ll check is that the dns entries all have an ingress on them

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Jun 5, 2021, at 10:25 AM, Valentin Kuznetsov ***@***.***> wrote:

﻿

I got report from Felipe Gómez-Cortés who claimed that DAS web UI provides different results for the following query:

site dataset=/ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM


After series of iterations I confirmed that this is the case using my dev environment. I identified that the problem is related to unability of DAS to contact with cms-rucio service yield the following errors:

2021/06/05 11:17:28 fetch.go:486: ERROR: fail to fetch http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#3ce2d95e-7168-11e6-9fb1-002590494fb0/datasets, retries 3, error Get "http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#3ce2d95e-7168-11e6-9fb1-002590494fb0/datasets": dial tcp: lookup cms-rucio.cern.ch: no such host
2021/06/05 11:17:28 fetch.go:486: ERROR: fail to fetch http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#c541fd04-7198-11e6-9fb1-002590494fb0/datasets, retries 3, error Get "http://cms-rucio.cern.ch/replicas/cms//ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM#c541fd04-7198-11e6-9fb1-002590494fb0/datasets": dial tcp: lookup cms-rucio.cern.ch: no such host


We need to identify the source of this issue. @ericvaandering<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ericvaandering&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=EHaoB-POFWGrYFvPXoj1bQ&m=cBW95wcg_2tkZclY6MIBUV8hW34_ILFUkkEW_VNXkc8&s=_k6wyLRlTTQVj9odpkn8Vcku6PHpP9Y0vToTY54nR6g&e=> any ideas?

**Comment by ericvaandering** [comment]
Didn't your hosts have some DNS issue before? Because I confirm that even from my desktop at home, cms-rucio.cern.ch resolves correctly to two IPs. And both those nodes in k8s have role=ingress. 

The error message sure looks like basic DNS lookup is failing, not that it's failing to connect or find a service on the IP address.

**Comment by vkuznet** [comment]
yes, the issue is intermittent, sometimes everything is fine while another attempt it is not. I can see see in production k8s and at my home running DAS from local laptop. I have suspicion that it is related to the concurrent load on DNS server(s).

**Comment by vkuznet** [comment]
I think it is old discussion of some racing conditions in Go network stack. I changed production server to use a queue and constraint it to max of 100 concurrent requests calls. After few test iterations I no longer see the problem. I'll leave ticket open and will check site queries to verify if it fix the problem.

**Comment by vkuznet** [comment]
The issue seems to be related to this open GoLang  [ticket](https://github.com/golang/go/issues/18588)

**Comment by vkuznet** [comment]
and I found yet another discussion on this topic, see the following [ticket](https://github.com/golang/go/issues/23866)

**Comment by vkuznet** [comment]
we no longer see this issue, closing
