### ISSUE TITLE
missing reqmgr info and relval dataset configuration 

### ISSUE THREAD

**Issue by slava77** [dmwm/das2go#35]
as an example for `config dataset=/RelValTTbar_14TeV/CMSSW_12_1_0_pre4-PU_121X_mcRun3_2021_realistic_v10_HighStat-v2/MINIAODSIM` I get
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=config+dataset%3D%2FRelValTTbar_14TeV%2FCMSSW_12_1_0_pre4-PU_121X_mcRun3_2021_realistic_v10_HighStat-v2%2FMINIAODSIM

<img width="770" alt="image" src="https://user-images.githubusercontent.com/4676718/139264385-73a03a34-0359-47c9-877a-3edec4977513.png">

Under `Config Name` link there is a generic https://cmsweb.cern.ch/das/request?input=config%3DReqMgr2&instance=prod/global , I would expect that it should return the actual reqmgr request pdmvserv_RVCMSSW_12_1_0_pre4TTbar_14TeV__HighStat_211020_131422_5228 at https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_RVCMSSW_12_1_0_pre4TTbar_14TeV__HighStat_211020_131422_5228

The following part, at `Config urls:` correctly picks up only one config out of 4 available in the request, as can be seen in the [reqmgr2 link](https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_RVCMSSW_12_1_0_pre4TTbar_14TeV__HighStat_211020_131422_5228) above
```
Config Cache List

    DQMConfigCacheID: 46713bf726160ce248142d29719c1878
    Task1: DigiPU_2021PU: ConfigCacheID: 46713bf726160ce248142d29719b6f22
    Task2: RecoPU_2021PU: ConfigCacheID: 46713bf726160ce248142d29719be2df
    Task3: Nano_2021PU: ConfigCacheID: 46713bf726160ce248142d29719c2eff 
```

**Comment by slava77** [comment]
OK, fair enough, I hope that the situation with the schema is understood and a good readable choice of config names in the config links will be made.

Thank you for the updates already made.

**Comment by vkuznet** [comment]
@amaltaro this request requires your review, especially since I don't know if configuration files follows specific schema. Here is it very important that documents should have static schema, and it is equally important to know up-front how certain names are created and where they will appear in a document. DAS always has this issues with different systems who do not provide the static schema. Please review and provide your feedback how certain configuration should be look-up in configuration docs, and provide schema definitions for these configuration files.

**Comment by amaltaro** [comment]
I am not sure I understand what is requested here.

WMCore/ReqMgr2 does define a request schema, their data types, how they are supposed to be constructed, default values, etc. However, we support multiple workflow/spec types, and each of them have its own peculiarities (also with a schema defined and enforced). In other words, there are key/value pairs that you will only find in TaskChain, others will only be available in StepChains, and ReReco will also be different. Please have a look at this documentation for further information:
https://github.com/dmwm/WMCore/wiki/Workflow-creation-and-assignment-definition#request-type-dependencies

`ConfigCacheID` or `DQMConfigCacheID` is meant to be a hash unique id, which points to a document in central CouchDB. Hence ReqMgr2 provides that id instead of the task/step to which it belongs to. It should be fairly easy to rename it in DAS to something like:
```
if RequestType == ReReco:
    rename config cache id to DataProcessing
elif RequestType == TaskChain:
    rename config cache id to the value in TaskName (note that you need to look at the right task dict)
elif RequestType == StepChain:
    rename config cache id to the value in StepName (note that you need to look at the right step dict)
```

**Comment by vkuznet** [comment]
@amaltaro thanks for providing this info, this is what is required. In this case, where I can find schema definitions for each individual workflows? Does diagram you showed represents all possible workflows in a system or there are others? Does naming conventions are fixed, i.e. use of CamelCase, like ConfigCacheID or DQMConfigCacheID. Where I can find all declared attributes of the schema? Does this area https://github.com/dmwm/WMCore/tree/master/doc/createSpecs represents all existing schema files? Once I have all answers and schema definitions I can proceed with implementation.

**Comment by vkuznet** [comment]
@slava77 , I deployed new version on production cluster which now shows IDs together with corresponding task/request name. It is shown like this:
```
Config urls: output-config-0 Request ids: 46713bf726160ce248142d29719be2df (RecoPU_2021PU), 46713bf726160ce248142d29719c2eff (Nano_2021PU), 46713bf726160ce248142d29719b6f22 (DigiPU_2021PU), 46713bf726160ce248142d29719c1878 (DQMConfigCacheID)
```
You may check your URL. Please confirm that now everything works and I can close the ticket.

**Comment by slava77** [comment]
looking at 
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=config+dataset%3D%2FRelValTTbar_14TeV%2FCMSSW_12_1_0_pre4-PU_121X_mcRun3_2021_realistic_v10_HighStat-v2%2FMINIAODSIM

I see
<img width="914" alt="image" src="https://user-images.githubusercontent.com/4676718/145692139-a27a34a8-2ac3-4e3a-bb5c-20656db82f78.png">
This is nice.

however the URLs are apparently malformed "https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/46713bf726160ce248142d29719be2df%20(RecoPU_2021PU)/configFile"
should instead be "https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/46713bf726160ce248142d29719be2df/configFile"

I would drop the hash from the hyperlink text and have just [RecoPU_2021PU](https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/46713bf726160ce248142d29719be2df/configFile)

Another thing, `ReqMgr info` link has a URL pointing to `https://cmsweb-k8s-prod.cern.ch/reqmgr2` is this the standard now or just a test instance?

**Comment by vkuznet** [comment]
thanks for spotting the issue with link, I didn't check it explicitly. Now it is fixed and I removed extra hashes from the link name. Please check and report again. Regarding URL for ReqMgr info, internally we do run it now on k8s and link is correct but I need to double check where we generate to confirm if we should point it to cmsweb or cmsweb-k8s-prod. I'll do it later.

**Comment by slava77** [comment]
@vkuznet 
Thank you for the update
The updates look good.

One minor thing I noticed is that there is some duplicate information now, in the URL [ output-config-0 ](https://cmsweb.cern.ch:8443/couchdb/reqmgr_config_cache/46713bf726160ce248142d29719c1878/configFile) we have the same information as [DQMConfigCacheID](https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/46713bf726160ce248142d29719c1878/configFile) ; note also the difference with `:8443` and without it in the two cases, respectively.

**Comment by vkuznet** [comment]
@slava77 , thanks for checking. I need to decide now if we need to show `Config urls` since we have `Request ids` info. I don't know yet if new info covers all output config urls. I need to check with different set of data. And, I'll fix port number too.

**Comment by amaltaro** [comment]
> https://github.com/dmwm/WMCore/tree/master/doc/createSpecs 

@vkuznet Hi Valentin, yes, this is the right place to see the request schema. It is likely missing the recent GPU* parameters though, I will have to update it in the coming days.

> Does diagram you showed represents all possible workflows in a system or there are others?

yes, `StoreResults` is planned to be deprecated though. So it's up to you if you want to support old workflows or not (likely less than 10 such workflows every year).

> Does naming conventions are fixed, i.e. use of CamelCase, like ConfigCacheID or DQMConfigCacheID.

yes, for spec attributes, we always use upper camel case.

**Comment by vkuznet** [comment]
@slava77 regarding `cmsweb-k8s-prod` link to ReqMgr. It is complicated and was introduced when DMWM team decided to separate cmsweb into two entities, one for end-users and another for production tools. Since DAS uses maps which has services URLs the direct links to services, like DBS or ReqMgr now point `cmsweb-k8s-prod` and internally DAS queries services via these URLs. For all other URs, like another DAS query, all links remain pointing to `cmsweb`. I don't want to write additional layer of redirection and current links are representing correct URLs, i.e. if it points to service on production cluster and if it uses DAS URL to access some query (which points to cmsweb).

I think this ticket can be closed, and I still need time to investigate if output-config-XXX links can be removed. Please confirm that we can close this ticket.

**Comment by slava77** [comment]
> Please confirm that we can close this ticket.

I'm fine to have this closed.
