### ISSUE TITLE
DAS queries to files and blocks returning 0

### ISSUE THREAD

**Issue by clelange** [dmwm/das2go#50]
Hi,

I'm trying to get some information regarding a dataset. The command worked earlier today, but now both web interface as well as CLI return that the dataset is empty and there are no blocks or files.
This is the query and response:

```
dasgoclient -query 'dataset dataset=/HIRun2015/HIHardProbes/RAW' -json
[
{"das":{"expire":1667919776,"instance":"prod/global","primary_key":"dataset.name","record":1,"services":["dbs3:filesummaries"]},"dataset":[{"max_ldate":null,"median_cdate":null,"median_ldate":null,"name":"/HIRun2015/HIHardProbes/RAW","nblocks":0,"nevents":0,"nfiles":0,"nlumis":0,"num_file":0,"num_lumi":0,"size":0}],"qhash":"3f5380f0c3bb4504ae3d5ca5431a0c69"}
]
```

`block` and `file` queries return nothing:

```
dasgoclient -query 'block dataset=/HIRun2015/HIHardProbes/RAW'
```

```
dasgoclient -query 'file dataset=/HIRun2015/HIHardProbes/RAW'
```

This might be some intermittent issue, but I don't know which CMS talk forum to use for that, which is why I'm reverting to GitHub...

**Comment by vkuznet** [comment]
Clemens, I think das returns you correct results, according to DBS database there is no such dataset in DB:
```
select * from cms_dbs3_prod_global_owner.datasets where dataset='/HIRun2015/HIHardProbes/RAW';

no rows selected
```
Then, I fetched all datasets in DBS DB and select those matching your query criteria and here is what I found:
```
,{"dataset":"/HIHardProbesPhotons/HIRun2015-v1/RAW"}
,{"dataset":"/HIHardProbes-Error/HIRun2015-v1/RAW"}
,{"dataset":"/HIHardProbesPeripheral/HIRun2015-v1/RAW"}
,{"dataset":"/HIHardProbes/HIRun2015-HighPtJet-PromptReco-v1/RAW-RECO"}
,{"dataset":"/HIHardProbes/HIRun2015-v1/RAW"}
```
Obviously, you either have dataset name wrong or someone was deleted this dataset from DBS.

And, regarding CMS talk forum, you can start either with computing operations or Data and Workflow Management forums to ask this kind of questions.

I'm closing this ticket now since it has nothing to do with DAS.

**Comment by clelange** [comment]
Uh, yes, sorry, my bad. At some point, I dropped `-v1` from my queries for whatever reason and that got me very confused. Thanks a lot for checking!
