### ISSUE TITLE
Integration DBS instance no longer available via cmsweb-testbed/das

### ISSUE THREAD

**Issue by amaltaro** [dmwm/das2go#9]
Valentin, I noticed both pre-prod and prod DAS have a list of prod/* dbs instances only. DAS testbed used to provide access to the integration database. Can that feature be restored?

**Comment by vkuznet** [comment]
Alan, could you please have a look at cmsweb-testbed now. Lina deployed new version of DAS where I implemented requested changes. I'll proceed with normal validation, but it would be nice if you'll have a look at integration instance output as you requested.

**Comment by vkuznet** [comment]
Alan, could you please place some queries on cmsweb-testbed. Lina deployed new version where I fixed the queries.

**Comment by amaltaro** [comment]
Valentin, I'll probably not have time to look at it before Friday evening, so I suggest you to check it yourself. Here are some example output dataset names:
```
  "OutputDatasets": [
    "/SingleElectron/CMSSW_7_4_0-HLTD_TaskChain_RelVal_Multicore_HG1809_Validation_TEST_Alan_v12-v11/RAW", 
    "/SingleElectron/CMSSW_7_4_0-RECODreHLT_TaskChain_RelVal_Multicore_HG1809_Validation_TEST_Alan_v12-v11/RECO", 
    "/SingleElectron/CMSSW_7_4_0-MINIAODDreHLT_TaskChain_RelVal_Multicore_HG1809_Validation_TEST_Alan_v12-v11/MINIAOD", 
    "/SingleElectron/CMSSW_7_4_0-RECODreHLT_TaskChain_RelVal_Multicore_HG1809_Validation_TEST_Alan_v12-v11/DQMIO", 
    "/SingleElectron/CMSSW_7_4_0-SiStripCalMinBias-RECODreHLT_TaskChain_RelVal_Multicore_HG1809_Validation_TEST_Alan_v12-v11/ALCARECO", 
    "/SingleElectron/CMSSW_7_4_0-SiStripCalZeroBias-RECODreHLT_TaskChain_RelVal_Multicore_HG1809_Validation_TEST_Alan_v12-v11/ALCARECO", 
    "/SingleElectron/CMSSW_7_4_0-TkAlMinBias-RECODreHLT_TaskChain_RelVal_Multicore_HG1809_Validation_TEST_Alan_v12-v11/ALCARECO"
  ], 
```

**Comment by amaltaro** [comment]
Those don't exist in int dbs, better taking
```
  "OutputDatasets": [
    "/RelValProdQCD_Pt_3000_3500_13/CMSSW_8_1_0-ProdQCD_Pt_3000_3500_13_TaskChain_MC_HG1809_Validation_TEST_Alan_v12-v11/GEN-SIM", 
    "/RelValProdQCD_Pt_3000_3500_13/CMSSW_8_1_0-RECOPRODUP15_TaskChain_MC_HG1809_Validation_TEST_Alan_v12-v11/AODSIM", 
    "/RelValProdQCD_Pt_3000_3500_13/CMSSW_8_1_0-RECOPRODUP15_TaskChain_MC_HG1809_Validation_TEST_Alan_v12-v11/DQMIO", 
    "/RelValProdQCD_Pt_3000_3500_13/CMSSW_8_1_0-RECOPRODUP15_TaskChain_MC_HG1809_Validation_TEST_Alan_v12-v11/MINIAODSIM"
  ], 
```

**Comment by amaltaro** [comment]
@vkuznet apparently this capability was dropped again somewhere in the near past. Can you please reopen and/or fix this issue again? Thanks

**Comment by vkuznet** [comment]
Alan,
the changes was done by me, see
https://github.com/dmwm/deployment/commit/3bc8230d436d724c19d615b41288630a596e21d9#diff-466bc1232382bc811a5059f211eed58f
since during deployment cycle I need to test DAS against production services.

So, we have a dilemma:

- during deployment I need/must test DAS against production services
- you need to point DAS to test instances (please remind me why do you need this)

I see two solutions here:

1. The only reasonable solution I see is to assign Lina a task that after integration tasks are done with DAS we can uncomment those lines
https://github.com/dmwm/deployment/blob/master/das/deploy#L25
and restart the DAS.

2. I change DAS deploy script to point DAS configs to testbed but use cmsweb
dev nodes. Such that if you or other can use cmsweb-dev.cern.ch/das/ which will
talk to CMS data-services on cmsweb-testbed.

**Comment by amaltaro** [comment]
Valentin, it's not that often, but sometimes I need to quickly check DBS data (in the integration database), for that I usually use DAS because it's much faster than looking for the API I need to query and maybe running a few queries to achieve what I need.

Can you clarify why you need to point testbed DAS to the production services? By doing so, you're not running a full integration of new version services, but you're only testing a new version of DAS integrated with possibly old version of other services. Not long ago Yuyi did a dump of production into integration DBS database. PhEDEx prod database is reachable via testbed, so I see no obvious reason why you would need that.

About the proposed solutions:
a) relying on the CMSWEB operator for switching instances isn't reliable 
b) cmsweb-dev no longer exists.

If this can't get fixed in a solid way, then we might let it be. It's not a show-stopper for me, but it's very handy when I need to check DBS data.

**Comment by vkuznet** [comment]
Alan,
I need to test DAS against production services since I'm testing against plenty
of them, like DBS, PhEDEx, Rucio, ReqMgr, CRIC, etc.
As you can see not all of them are on testbed and not all data are available.

But I think for your use case you should be better using dasgoclient instead of
das web. It would be much easier for you, faster and you can use it without
waiting for DAS deployment on testbed.

Just use it as following

dasgoclient -query=<your dasquery> -host=https://cmsweb-testbed.cern.ch

doing so the dasgoclient will talk to data-services from cmsweb-testbed.cern.ch

Can you try it out? The dasgoclient is available in every CMSSW release, here is
direct path: /cvmfs/cms.cern.ch/common/dasgoclient

Or, you can get static executable and use it for your tests from your own
environment.

Best,
Valentin.

**Comment by vkuznet** [comment]
no longer relevant, closing.
